### ISSUE TITLE
Permission to fork the project for giscus

### ISSUE THREAD

**Issue by laymonage** [TomokiMiyauci/utterances-component#10]
Hey, thanks for making this component library!

I'm currently making [giscus](https://giscus.app), a project similar to utterances but it uses GitHub Discussions instead of Issues. I'm planning to create React, Vue, and Svelte components for it. I've only made one for [React](https://github.com/giscus/react-giscus) so far. I'm sure that the components for the three frameworks/libraries will share some code between one another. As this monorepo seems to already have that kind of set up, I'm thinking about forking it for giscus.

I will have a different approach for the components, though. Instead of injecting a `<script>` element, they will contain the logic of the `<script>` element instead, which means that the component will directly load the `<iframe>` instead of a `<script>`.

I know that this library is open source and I don't need your explicit permission to fork it, but I'm just letting you know about it. Feel free to close this issue :slightly_smiling_face: 

Thanks again!

**Comment by TomokiMiyauci** [comment]
I hope this project has been helpful✨

I'm interested in your project.
If there is anything I can do to help, please let me know.

This issue is closed, but if you have any comments, feel free to make them.
